CREATE TABLE [dbo].[Mail]
(
	[Id] INT IDENTITY (1, 1) NOT NULL CONSTRAINT [PK_Mail] PRIMARY KEY,
	[CreatedOn] DATETIME NOT NULL CONSTRAINT [DF_Mail_CreatedOn] DEFAULT(GETUTCDATE()),
	[Recipient] VARCHAR(255) NOT NULL,
	[Subject] NVARCHAR(255) NOT NULL,
	[Body] NVARCHAR(2048) NOT NULL,
)
